### ISSUE TITLE
Backslashes need to be escaped in Point values

### ISSUE THREAD

**Issue by zorac** [influxdata/influxdb-php#125]
Backslashes need to be escaped in point values where they immediately precede a double quote, or where they're the last character of the value. Example errors:

value=a b
<No error>

value=a\b
<No error>

value=a\"b
Warning: Uncaught InfluxDB\Exception: HTTP Code 400 {"error":"unable to parse 'test value=\"a\\\\\"b\"': unbalanced quotes"}
 in /app/vendor/influxdb/influxdb-php/src/InfluxDB/Database.php:177
Stack trace:
#0 /app/vendor/influxdb/influxdb-php/src/InfluxDB/Database.php(142): InfluxDB\Database->writePayload(Array, 'n', NULL)

value=a b\
Warning: Uncaught InfluxDB\Exception: HTTP Code 400 {"error":"unable to parse 'test value=\"a b\\\"': unbalanced quotes"}
 in /app/vendor/influxdb/influxdb-php/src/InfluxDB/Database.php:177
Stack trace:
#0 /app/vendor/influxdb/influxdb-php/src/InfluxDB/Database.php(142): InfluxDB\Database->writePayload(Array, 'n', NULL)

**Comment by zorac** [comment]
PR #126 contains a fix for this.
